# Generated by Django 4.2.9 on 2024-02-17 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scentprofile', '0002_alter_product_scentoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductScent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('scentoptions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scentprofile.scentprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
