# Generated by Django 4.2.9 on 2024-02-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scentprofile', '0004_productscent_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductScent',
        ),
    ]
