# Generated by Django 4.2.9 on 2024-02-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_faq_qa_faqcategory_delete_faq_faq_qa_faq_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq_qa',
            options={'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'verbose_name_plural': 'FAQ Categories'},
        ),
    ]
