# Generated by Django 4.2.9 on 2024-02-17 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_scent_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='scent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.scentprofile'),
        ),
    ]
