# Generated by Django 4.2.9 on 2024-02-17 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scentprofile', '0003_productscent_delete_product'),
        ('products', '0009_alter_product_scent_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='scent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scentprofile.scentprofile'),
        ),
    ]
