# Generated by Django 4.2.9 on 2024-02-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScentProfile',
        ),
    ]
